### ISSUE TITLE
Unhandled exception: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/”

### ISSUE THREAD

**Issue by pablojimpas** [jpnurmi/geoclue.dart#1]
Hi! Thanks for building this package, I've encountered an issue testing it.

I've `/usr/lib/geoclue-2.0/demos/agent` and the `where-am-i` demo that comes with geoclue works fine, however, if I try to run the provided example in this package I get the following error:

```
Unhandled exception:
org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/”
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1128:13)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:628:12)
<asynchronous suspension>
#2      DBusRemoteObject.getAllProperties (package:dbus/src/dbus_remote_object.dart:146:18)
<asynchronous suspension>
#3      GeoClueClient._buildLocation (package:geoclue/src/client.dart:146:24)
<asynchronous suspension>
#4      main (file:///home/polo/geoclue.dart/example/bin/example.dart:9:3)
<asynchronous suspension>
```

What do you think is going on?

**Comment by jpnurmi** [comment]
Hey, thanks for testing. What kind of setup and what geoclue version do you have? I'm developing on Ubuntu 22.04 with geoclue-2.0 2.5.7-3ubuntu2.

**Comment by pablojimpas** [comment]
> What kind of setup and what geoclue version do you have?

I tested this on Artix Linux with geoclue 2.6.0. I think this is the [where-am-i demo](https://cgit.freedesktop.org/geoclue/plain/demo/where-am-i.c) that it ships by default and works well in my system.

**Comment by jpnurmi** [comment]
I was able to reproduce the issue by toggling the "org.gnome.system.location enabled" setting. Sometimes GeoClue would return an unknown location, that was not handled as appropriate.

**Comment by pablojimpas** [comment]
> I was able to reproduce the issue by toggling the "org.gnome.system.location enabled" setting

For me changing this to true or false doesn't make a difference. I wonder why the original C example works in my system, may be worth looking at the differences in the implementation.

**Comment by jpnurmi** [comment]
I changed the example to wait 10s for location updates. Does it make any difference?

**Comment by pablojimpas** [comment]
> Does it make any difference?

Okey, now it works beautifully, great job!

~~PS. Now I see differences in accuracy between the C version and this example (even setting the requested accuracy level to `exact`). The Dart version at best gives me 3010.0 meters of accuracy and the C version 10.0 meters. Maybe it's a conversion issue or something similar?~~ Sorry, that was my fault, I was calling `setRequestedAccuracyLevel` after `start`.
